"""Multinational personal-name data for generating personalized password
wordlists.

Used by generate_wordlists.py to build candidates like
"Marie.1990", "dupont123", "JMartin85" etc. from realistic
first-name/last-name/birth-date combinations across many nationalities.
"""

# First names by nationality (top ~40 each)
FIRST_NAMES = {
    "french": [
        "Marie", "Jean", "Pierre", "Michel", "Nathalie", "Isabelle",
        "Sophie", "Julie", "Julien", "Nicolas", "Thomas", "Camille",
        "Laura", "Sarah", "Kevin", "Anthony", "David", "Francois",
        "Lucie", "Emma", "Hugo", "Lucas", "Manon", "Chloe", "Antoine",
        "Alexandre", "Pauline", "Mathieu", "Marine", "Florian",
        "Quentin", "Maxime", "Clara", "Lena", "Baptiste", "Vincent",
        "Laurent", "Celine", "Sandra", "Jeremy", "Benjamin", "Amandine",
    ],
    "english": [
        "James", "John", "Robert", "Michael", "William", "David",
        "Richard", "Joseph", "Thomas", "Charles", "Mary", "Patricia",
        "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica",
        "Sarah", "Karen", "Daniel", "Matthew", "Andrew", "Joshua",
        "Christopher", "Ashley", "Amanda", "Melissa", "Stephanie",
        "Nicole", "Tyler", "Ryan", "Jack", "Oliver", "Emily", "Emma",
        "Charlotte", "Ava", "Sophia", "Mia",
    ],
    "spanish": [
        "Alejandro", "Carlos", "Diego", "Fernando", "Francisco",
        "Gabriel", "Javier", "Jorge", "Jose", "Juan", "Luis", "Manuel",
        "Miguel", "Pablo", "Pedro", "Rafael", "Sergio", "Vicente",
        "Antonio", "Angel", "Carmen", "Dolores", "Isabel", "Lucia",
        "Maria", "Marta", "Paula", "Rosa", "Sara", "Silvia", "Teresa",
        "Valentina", "Sofia", "Camila", "Daniela", "Elena", "Adriana",
        "Andrea", "Laura", "Patricia",
    ],
    "german": [
        "Alexander", "Andreas", "Christian", "Daniel", "David",
        "Florian", "Jan", "Jonas", "Julian", "Kevin", "Lukas", "Manuel",
        "Markus", "Martin", "Michael", "Moritz", "Nico", "Niklas",
        "Paul", "Philipp", "Sebastian", "Simon", "Stefan", "Thomas",
        "Tobias", "Anna", "Julia", "Katharina", "Laura", "Lea", "Lena",
        "Lisa", "Marie", "Melanie", "Nadine", "Nicole", "Sandra",
        "Sarah", "Stefanie", "Vanessa",
    ],
    "italian": [
        "Alessandro", "Andrea", "Angelo", "Antonio", "Carlo", "Davide",
        "Domenico", "Fabio", "Federico", "Francesco", "Giovanni",
        "Giuseppe", "Lorenzo", "Luca", "Marco", "Matteo", "Michele",
        "Nicola", "Paolo", "Roberto", "Simone", "Stefano", "Vincenzo",
        "Anna", "Alessia", "Barbara", "Chiara", "Daniela", "Elena",
        "Elisa", "Francesca", "Giulia", "Ilaria", "Laura", "Lucia",
        "Maria", "Martina", "Monica", "Paola", "Sara", "Sofia",
    ],
    "arabic": [
        "Mohamed", "Ahmed", "Ali", "Omar", "Hassan", "Hussein",
        "Youssef", "Ibrahim", "Khaled", "Mahmoud", "Tarek", "Sami",
        "Karim", "Nabil", "Walid", "Hamza", "Amir", "Fadi", "Rami",
        "Bilal", "Fatima", "Aisha", "Mariam", "Layla", "Nour", "Salma",
        "Huda", "Amira", "Nadia", "Rania", "Samira", "Yasmin",
        "Zainab", "Hana", "Dalia", "Mona", "Lina", "Rana", "Sara",
        "Dina",
    ],
    "portuguese": [
        "Joao", "Pedro", "Lucas", "Gabriel", "Rafael", "Matheus",
        "Bruno", "Felipe", "Gustavo", "Diego", "Rodrigo", "Thiago",
        "Carlos", "Marcos", "Andre", "Paulo", "Ricardo", "Eduardo",
        "Fabricio", "Marcelo", "Ana", "Maria", "Juliana", "Camila",
        "Fernanda", "Larissa", "Beatriz", "Mariana", "Isabela",
        "Amanda", "Patricia", "Bruna", "Jessica", "Carolina", "Leticia",
        "Vanessa", "Aline", "Renata", "Sabrina", "Tatiane",
    ],
    "russian": [
        "Alexander", "Dmitri", "Sergei", "Andrei", "Alexei", "Ivan",
        "Nikolai", "Mikhail", "Vladimir", "Pavel", "Yuri", "Viktor",
        "Igor", "Oleg", "Roman", "Anton", "Maxim", "Denis", "Artem",
        "Kirill", "Anastasia", "Elena", "Olga", "Tatiana", "Irina",
        "Natalia", "Svetlana", "Ekaterina", "Maria", "Anna", "Yulia",
        "Marina", "Daria", "Vera", "Polina", "Ksenia", "Alina",
        "Victoria", "Ludmila", "Galina",
    ],
    "turkish": [
        "Mehmet", "Mustafa", "Ahmet", "Ali", "Huseyin", "Hasan",
        "Ibrahim", "Osman", "Yusuf", "Murat", "Emre", "Can", "Burak",
        "Kerem", "Onur", "Baris", "Serkan", "Volkan", "Tolga", "Oguz",
        "Ayse", "Fatma", "Emine", "Zeynep", "Elif", "Merve", "Esra",
        "Hatice", "Sevgi", "Gul", "Derya", "Selin", "Melis", "Ceren",
        "Buse", "Yasemin", "Ozlem", "Aylin", "Deniz", "Sibel",
    ],
    "dutch": [
        "Daan", "Sem", "Lucas", "Jesse", "Thomas", "Bram", "Lars",
        "Tim", "Ruben", "Max", "Thijs", "Stijn", "Robin", "Niels",
        "Sander", "Wouter", "Jeroen", "Maarten", "Pieter", "Bas",
        "Emma", "Julia", "Sophie", "Lotte", "Lisa", "Sanne", "Anouk",
        "Eva", "Fleur", "Anna", "Lieke", "Nina", "Roos", "Mila",
        "Sara", "Lynn", "Noor", "Femke", "Sofie", "Eline",
    ],
    "polish": [
        "Jakub", "Mateusz", "Kacper", "Szymon", "Filip", "Bartosz",
        "Michal", "Piotr", "Krzysztof", "Tomasz", "Pawel", "Marcin",
        "Lukasz", "Marek", "Adam", "Grzegorz", "Dawid", "Karol",
        "Wojciech", "Jan", "Anna", "Katarzyna", "Magdalena", "Agnieszka",
        "Marta", "Monika", "Ewa", "Alicja", "Julia", "Zuzanna",
        "Maja", "Oliwia", "Aleksandra", "Natalia", "Karolina",
        "Dominika", "Patrycja", "Weronika", "Paulina", "Agata",
    ],
}

# Last names by nationality
LAST_NAMES = {
    "french": [
        "Martin", "Bernard", "Thomas", "Petit", "Robert", "Richard",
        "Durand", "Dubois", "Moreau", "Laurent", "Simon", "Michel",
        "Lefebvre", "Leroy", "Roux", "David", "Bertrand", "Morel",
        "Fournier", "Girard", "Bonnet", "Dupont", "Lambert", "Fontaine",
        "Rousseau", "Vincent", "Muller", "Lefevre", "Faure", "Andre",
        "Mercier", "Blanc", "Guerin", "Boyer", "Garnier", "Chevalier",
        "Francois", "Legrand", "Gauthier", "Garcia", "Perrin", "Rey",
    ],
    "english": [
        "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia",
        "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez",
        "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor",
        "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
        "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis",
        "Robinson", "Walker", "Young", "Allen", "King", "Wright",
        "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green",
    ],
    "spanish": [
        "Garcia", "Rodriguez", "Gonzalez", "Fernandez", "Lopez",
        "Martinez", "Sanchez", "Perez", "Gomez", "Martin", "Jimenez",
        "Ruiz", "Hernandez", "Diaz", "Moreno", "Munoz", "Alvarez",
        "Romero", "Alonso", "Gutierrez", "Navarro", "Torres",
        "Dominguez", "Vazquez", "Ramos", "Gil", "Ramirez", "Serrano",
        "Blanco", "Molina", "Morales", "Suarez", "Ortega", "Delgado",
        "Castro", "Ortiz", "Rubio", "Marin", "Sanz", "Nunez",
    ],
    "german": [
        "Muller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer",
        "Wagner", "Becker", "Schulz", "Hoffmann", "Schafer", "Koch",
        "Bauer", "Richter", "Klein", "Wolf", "Schroder", "Neumann",
        "Schwarz", "Zimmermann", "Braun", "Kruger", "Hofmann", "Hartmann",
        "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier",
        "Lehmann", "Schmid", "Schulze", "Maier", "Kohler", "Herrmann",
        "Konig", "Walter", "Mayer", "Huber",
    ],
    "italian": [
        "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano",
        "Colombo", "Ricci", "Marino", "Greco", "Bruno", "Gallo",
        "Conti", "De Luca", "Mancini", "Costa", "Giordano", "Rizzo",
        "Lombardi", "Moretti", "Barbieri", "Fontana", "Santoro",
        "Mariani", "Rinaldi", "Caruso", "Ferrara", "Galli", "Martini",
        "Leone", "Longo", "Gentile", "Martinelli", "Vitale", "Lombardo",
        "Serra", "Coppola", "De Santis", "D'Angelo", "Marchetti",
    ],
    "arabic": [
        "Al-Farsi", "Al-Hassan", "Al-Amin", "Ben Ali", "Ben Salah",
        "Ben Ahmed", "Al-Khalil", "Al-Rashid", "Haddad", "Nasser",
        "Khalil", "Aziz", "Salem", "Hamdan", "Farah", "Khoury",
        "Sabbagh", "Naim", "Habib", "Awad", "Mansour", "Suleiman",
        "Odeh", "Shaheen", "Barakat", "Yousef", "Moussa", "Nakhleh",
        "Tahan", "Zaydan", "Karam", "Issa", "Qasim", "Rahman",
        "Saeed", "Harb", "Zaid", "Fadel", "Malouf", "Abdo",
    ],
    "portuguese": [
        "Silva", "Santos", "Oliveira", "Souza", "Lima", "Pereira",
        "Ferreira", "Costa", "Rodrigues", "Almeida", "Nascimento",
        "Araujo", "Ribeiro", "Fernandes", "Carvalho", "Gomes",
        "Martins", "Rocha", "Barbosa", "Ribeiro", "Alves", "Monteiro",
        "Cardoso", "Mendes", "Pinto", "Correia", "Marques", "Melo",
        "Freitas", "Teixeira", "Cavalcanti", "Campos", "Moreira",
        "Dias", "Moura", "Sales", "Castro", "Azevedo", "Farias",
        "Barros",
    ],
    "russian": [
        "Ivanov", "Smirnov", "Kuznetsov", "Popov", "Vasiliev",
        "Petrov", "Sokolov", "Mikhailov", "Novikov", "Fedorov",
        "Morozov", "Volkov", "Alekseev", "Lebedev", "Semenov",
        "Egorov", "Pavlov", "Kozlov", "Stepanov", "Nikolaev",
        "Orlov", "Andreev", "Makarov", "Nikitin", "Zakharov",
        "Zaitsev", "Soloviev", "Borisov", "Yakovlev", "Grigoriev",
        "Romanov", "Vorobiev", "Sergeev", "Fomin", "Tkachev",
        "Gusev", "Kiselev", "Sorokin", "Titov", "Kovalev",
    ],
    "turkish": [
        "Yilmaz", "Kaya", "Demir", "Celik", "Sahin", "Yildiz",
        "Ozturk", "Aydin", "Ozdemir", "Arslan", "Dogan", "Kilic",
        "Aslan", "Cetin", "Kara", "Koc", "Kurt", "Ozkan", "Simsek",
        "Sahin", "Polat", "Ozer", "Korkmaz", "Bulut", "Aksoy",
        "Erdogan", "Ozturk", "Acar", "Yavuz", "Ozbay", "Aydogdu",
        "Tekin", "Karaca", "Turan", "Kaplan", "Aydemir", "Sari",
        "Ak", "Gunes", "Coban",
    ],
    "dutch": [
        "De Jong", "Jansen", "De Vries", "Van den Berg", "Van Dijk",
        "Bakker", "Janssen", "Visser", "Smit", "Meijer", "De Boer",
        "Mulder", "De Groot", "Bos", "Vos", "Peters", "Hendriks",
        "Van Leeuwen", "Dekker", "Brouwer", "De Wit", "Dijkstra",
        "Smits", "De Graaf", "Van der Meer", "Kok", "Jacobs",
        "Willems", "Van Dam", "Van Vliet", "De Ruiter", "Van der Wal",
        "Kuiper", "Van Beek", "Vermeulen", "De Haan", "Van den Heuvel",
        "Van der Linden", "Wolters", "Van der Laan",
    ],
    "polish": [
        "Nowak", "Kowalski", "Wisniewski", "Wojcik", "Kowalczyk",
        "Kaminski", "Lewandowski", "Zielinski", "Szymanski", "Wozniak",
        "Dabrowski", "Kozlowski", "Jankowski", "Mazur", "Wojciechowski",
        "Kwiatkowski", "Krawczyk", "Kaczmarek", "Piotrowski",
        "Grabowski", "Nowakowski", "Pawlak", "Michalski", "Adamczyk",
        "Dudek", "Zajac", "Wieczorek", "Jablonski", "Krol", "Majewski",
        "Olszewski", "Stachowiak", "Malinowski", "Pawlowski",
        "Witkowski", "Walczak", "Stepien", "Gorski", "Rutkowski",
        "Michalak",
    ],
}

# Nationalities available
NATIONALITIES = sorted(FIRST_NAMES.keys())
